---
###########################
# Setup Kubernetes client
###########################

# Expects `kubernetes_api_endpoint` to be defined passed in
# as `--extra-vars "kubernetes_api_endpoint=xxxx"`

- hosts: localhost
  connection: local

  vars:
    kubernetes_api_endpoint: 10.0.20.20
    kubernetes_api_endpoint_port: 6443
    kubernetes_cluster_name: "khw"
    certificate_path: "{{ playbook_dir }}/../cert"
    kubectl_user: "admin"

  tasks:

  - name: Check certificate file
    stat:
      path: "{{ certificate_path }}/ca.pem"
    register: cert

  - assert:
      that: "cert.stat.exists == True"

  - name: Set kubectl endpoint
    shell: "kubectl config set-cluster {{ kubernetes_cluster_name }} --certificate-authority={{ certificate_path }}/ca.pem --embed-certs=true --server=https://{{ kubernetes_api_endpoint }}:{{ kubernetes_api_endpoint_port }}"

  - name: Set kubectl credentials
    shell: "kubectl config set-credentials {{kubectl_user}} \
            --client-certificate={{ certificate_path }}/admin.pem \
            --client-key={{ certificate_path }}/admin-key.pem \
            --embed-certs=true"

  - name: Set kubectl default context
    shell: "kubectl config set-context khw --cluster={{ kubernetes_cluster_name }} --user={{ kubectl_user }}"

  - name: Switch kubectl to default context
    shell: "kubectl config use-context khw"
