---
- name: Create temp directory for helm
  command: mktemp -d /tmp/openshift-ansible-monitoring-XXXXXXX
  register: mktemp
  changed_when: False

- name: Deploy grafana resources
  copy:
    dest: "{{ mktemp.stdout }}/grafana-values.yaml"
    src: "grafana-values.yaml"

- name: Set monitoring project
  oc_project:
    state: present
    name: "monitoring"
    node_selector: "{{ openshift_giffgaff_monitoring_nodeselector | default('region=infra') }}"

- name: fetch grafana grafana
  command: "helm fetch {{item}}"
  with_items:
  - stable/grafana
  - stable/prometheus

- name: install grafana
  command: "helm install -f {{ mktemp.stdout }}/grafana-values.yaml stable/grafana --name gg --namespace monitoring --tiller-namespace tiller --wait"