---
#####################
# Install Python
#####################

- hosts: all
  gather_facts: false # As Python is not yet installed, we cannot gather host facts
  tasks:
    - name: Apt update
      raw: "apt-get update"
      become: true
      retries: 10
      delay: 20

    - name: Install Python
      raw: "apt-get install -y python"
      become: true
      retries: 10
      delay: 20

#######################
# Setup K8s components
#######################

- hosts: etcds
  roles:
    - common
    - etcd

- hosts: masters
  roles:
    - common
    - master

#- hosts: workers
#  roles:
#    - common
#    - worker
