---
#####################
# Install Python
#####################

- hosts: masters,workers
  gather_facts: false # As Python is not yet installed, we cannot gather host facts
  become: true
  roles:
    - bootstrap-kubeadm

- hosts: masters
  become: true
  tasks:
    - name: kubeadm init kubernetes_pod_cluster_cidr
      command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-checks-errors"
      register: kubeadmin_init_output

    - name: setup config for kubectl
      command: bash -c "mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config"

    - name: download flannel pod network
      get_url:
        url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
        dest: "/etc/kubernetes"

    - name: create flannel pod network
      command: kubectl apply -f /etc/kubernetes/kube-flannel.yml

    - name: Wait 300 seconds for port 8080 to become open on the host, don't start checking for 10 seconds
      wait_for:
        port: 8080

    - name: Verify Kubernetes status
      shell: kubectl get componentstatuses
      register: cmd_result
      retries: 5
      delay: 20
      become: true

    - assert:
        that:
          - "'scheduler            Healthy' in cmd_result.stdout"
          - "'controller-manager   Healthy' in cmd_result.stdout"
          - "'etcd-0               Healthy' in cmd_result.stdout"


#- hosts: workers
#  become: true
#  tasks:
#    - name: kubeadm join
#      command: "kubeadm join --token <token> <master-ip>:<master-port> --discovery-token-ca-cert-hash sha256:<hash>"