---
- hosts: masters,workers
  gather_facts: false # As Python is not yet installed, we cannot gather host facts
  become: true
  roles:
    - bootstrap-kubeadm

- hosts: masters
  become: true
  tasks:
    - name: kubeadm init kubernetes_pod_cluster_cidr
      command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --token {{kubetoken.stdout}}  --kubernetes-version {{kubernetes_version}}"
      register: kubeadmin_init_output
      ignore_errors: true

    - name: setup config for kubectl
      command: bash -c "mkdir -p $HOME/.kube && cp -f /etc/kubernetes/admin.conf $HOME/.kube/config && chown $(id -u):$(id -g) $HOME/.kube/config"

    - name: download flannel pod network
      get_url:
        url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
        dest: "/etc/kubernetes"

    - name: create flannel pod network
      command: kubectl apply -f /etc/kubernetes/kube-flannel.yml

    - name: Verify Kubernetes status
      shell: kubectl get componentstatuses
      register: cmd_result
      retries: 5
      delay: 20
      become: true

    - assert:
        that:
          - "'scheduler            Healthy' in cmd_result.stdout"
          - "'controller-manager   Healthy' in cmd_result.stdout"
          - "'etcd-0               Healthy' in cmd_result.stdout"

- hosts: workers
  become: true
  tasks:
    - name: kubeadm join
      command: "kubeadm join --token {{kubetoken.stdout}} 10.0.20.20:6443 --discovery-token-unsafe-skip-ca-verification"


- hosts: masters[0]
  become: true
  tasks:
    - name: smoke test
      command: kubectl run nginx --image=nginx
    - command: kubectl rollout status deployment/nginx
    - command: kubectl delete deployment/nginx